[workspace]
resolver = "2"

members = [
    "afb-librs",
    "afb-samples",
    "afb-tests",
]

[workspace.package]
# hérité par les crates avec `license.workspace = true`
edition = "2021"
license = "MIT OR Apache-2.0"
